<template>
    <v-data-table
            :headers="headers"
            :items="desserts"
            :sort-by="['calories', 'fat']"
            :sort-desc="[false, true]"
            multi-sort
            class="elevation-1"
    ></v-data-table>
</template>

<script>
    export default {
        name: "AnalyticsDataTable",
        data () {
            return {
                headers: [
                    {
                        text: 'Competitors pricing',
                        align: 'left',
                        sortable: false,
                        value: 'name',
                    },
                    { text: 'date ', value: 'date' },
                    { text: 'date2 ', value: 'date2' },
                    { text: 'date3 ', value: 'date3' },
                    { text: 'date4 ', value: 'date4' },
                    { text: 'date5 ', value: 'date5' },
                    { text: 'date6 ', value: 'date6' },
                    { text: 'date7 ', value: 'date7' },
                    { text: 'date8 ', value: 'date8' },
                    { text: 'date9 ', value: 'date9' },
                    { text: 'date10 ', value: 'date10' },
                    { text: 'date11 ', value: 'date11' },
                    { text: 'date12 ', value: 'date12' },
                    { text: 'date13 ', value: 'date13' },
                    { text: 'date14 ', value: 'date14' },
                    { text: 'date15 ', value: 'date15' },
                    { text: 'date16 ', value: 'date16' },
                    { text: 'date17 ', value: 'date17' },
                    { text: 'date18 ', value: 'date18' },
                    { text: 'date19 ', value: 'date19' },
                    { text: 'date20 ', value: 'date20' },
                    { text: 'date21 ', value: 'date21' },
                    { text: 'date22 ', value: 'date22' },
                    { text: 'date23 ', value: 'date23' },
                    { text: 'date24 ', value: 'date24' },
                    { text: 'date25 ', value: 'date25' },
                    { text: 'date26 ', value: 'date26' },
                    { text: 'date27 ', value: 'date27' },
                    { text: 'date28 ', value: 'date28' },
                    { text: 'date29 ', value: 'date29' },
                    { text: 'date30 ', value: 'date30' },
                ],
                desserts: [
                    {
                        name: 'Sample Hotel 1',
                        date: '11',
                        date2: '12',
                        date3: '31',
                        date4: '12',
                        date5: '11',
                        date6: '15',
                        date7: '17',
                        date8: '18',
                        date9: '211',
                        date10: '11',
                        date11: '17',
                        date12: '81',
                        date13: '16',
                        date14: '41',
                        date15: '12',
                        date16: '71',
                        date17: '91',
                        date18: '10',
                        date19: '671',
                        date20: '13',
                        date21: '11',
                        date22: '12',
                        date23: '51',
                        date24: '71',
                        date25: '91',
                        date26: '15',
                        date27: '31',
                        date28: '16',
                        date29: '17',
                        date30: '18',
                    },
                    {
                        name: 'Sample Hotel 3',
                        date: '12',
                        date2: '12',
                        date3: '31',
                        date4: '12',
                        date5: '11',
                        date6: '15',
                        date7: '17',
                        date8: '18',
                        date9: '211',
                        date10: '11',
                        date11: '17',
                        date12: '81',
                        date13: '16',
                        date14: '41',
                        date15: '12',
                        date16: '71',
                        date17: '91',
                        date18: '10',
                        date19: '671',
                        date20: '13',
                        date21: '11',
                        date22: '12',
                        date23: '51',
                        date24: '71',
                        date25: '91',
                        date26: '15',
                        date27: '31',
                        date28: '16',
                        date29: '17',
                        date30: '18',
                    },
                    {
                        name: 'Sample Hotel 2',
                        date: '1',
                        date2: '12',
                        date3: '31',
                        date4: '12',
                        date5: '11',
                        date6: '15',
                        date7: '17',
                        date8: '18',
                        date9: '211',
                        date10: '11',
                        date11: '17',
                        date12: '81',
                        date13: '16',
                        date14: '41',
                        date15: '12',
                        date16: '71',
                        date17: '91',
                        date18: '10',
                        date19: '671',
                        date20: '13',
                        date21: '11',
                        date22: '12',
                        date23: '51',
                        date24: '71',
                        date25: '91',
                        date26: '15',
                        date27: '31',
                        date28: '16',
                        date29: '17',
                        date30: '18',
                    },
                ],
            }
        },
    }
</script>

<style scoped>

</style>